

##LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL
## automatically generated by 26-special_threshold_calculations.ipynb
##TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT

import numpy as np

import tropy.analysis_tools.statistics as stats

from coorga.inout.atlantic_masking import atlantic_masking

####################################################################
####################################################################

def special_threshold_calculations(lon, lat, f, method = None):
    '''
    Calculates a special threshold for a field.
    '''
    
    if method ==  'relative50_for_mass_flux':
        
        # peform region masking
        fm = atlantic_masking(lon, lat, f, mask_value = 0.)

        # calculate cummulative data sum
        fp = np.where(fm > 0., fm, 0.)
        csf = stats.cumsum_data_fraction(fp)
        
        thresh = fp[csf < 50.].min()
        
    return thresh
